sonar.projectKey=cascade
sonar.projectName=Cascade
sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/*.d.ts
sonar.coverage.exclusions=src/cli.ts,src/**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
